---
platform: linux

image: docker:///bosh/init

inputs:
- name: bosh-init
  path: gopath/src/github.com/cloudfoundry/bosh-init
- name: version-semver

outputs:
- name: compiled-linux

params:
  GOOS:   linux
  GOARCH: amd64

run:
  path: gopath/src/github.com/cloudfoundry/bosh-init/ci/tasks/build.sh
